os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - 'node'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=g++-6; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
script:
  - node node_modules/mocha/bin/mocha test/testPackageFiles.js --exit
  - node node_modules/mocha/bin/mocha test/testAdapterWrapperNoInfo.js --exit
  - node node_modules/mocha/bin/mocha test/testAdapterWrapperWithInfo.js --exit
  - rm -rf tmp/node_modules/iobroker.ham/node_modules/homebridge-http-webhooks
  - rm -rf tmp/node_modules/iobroker.ham/node_modules/homebridge-sun-position
  - node node_modules/mocha/bin/mocha test/testAdapterZLocal.js --exit
  - rm -rf tmp/node_modules/iobroker.ham/node_modules/homebridge-http-webhooks
  - rm -rf tmp/node_modules/iobroker.ham/node_modules/homebridge-sun-position
  - rm -rf tmp/node_modules/iobroker.ham/node_modules/homebridge
  - npm install -g homebridge@1.1.1
  - npm install -g homebridge-http-webhooks
  - npm install -g homebridge-sun-position
  - export NODE_GLOBAL_DIR=$(npm root -g)
  - node node_modules/mocha/bin/mocha test/testAdapterXGlobal.js --exit
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libavahi-compat-libdnssd-dev
