version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: '14'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjourcore2.msi'
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjoursdksetup.exe'
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - 'set BONJOUR_SDK_HOME=C:\Program Files\Bonjour SDK'
  - npm ci
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - node node_modules\mocha\bin\mocha test\testPackageFiles.js --exit
  - node node_modules\mocha\bin\mocha test\testAdapterWrapperNoInfo.js --exit
  - node node_modules\mocha\bin\mocha test\testAdapterWrapperWithInfo.js --exit
  - ps: rm tmp\node_modules\iobroker.ham\node_modules\homebridge-http-webhooks -r -fo
  - ps: rm tmp\node_modules\iobroker.ham\node_modules\homebridge-sun-position -r -fo
  - node node_modules\mocha\bin\mocha test\testAdapterZLocal.js --exit & exit 0
  - ps: rm tmp\node_modules\iobroker.ham\node_modules\homebridge-http-webhooks -r -fo
  - ps: rm tmp\node_modules\iobroker.ham\node_modules\homebridge-sun-position -r -fo
  - ps: rm tmp\node_modules\iobroker.ham\node_modules\homebridge -r -fo
  - npm install -g homebridge@1.1.1
  - npm install -g homebridge-http-webhooks
  - npm install -g homebridge-sun-position
  - for /f "delims=" %%A in ('npm root -g') do set "NODE_GLOBAL_DIR=%%A"
  - node node_modules\mocha\bin\mocha test\testAdapterXGlobal.js --exit
build: 'off'
